FROM flexconstructor/docker-flexunit
MAINTAINER FlexConstructor <flexconstructor@gmail.com>
#ENV FLASH_PLAYER_EXE /usr/bin/gflashplayer
#USER root
#WORKDIR /tmp
#COPY run.sh run.sh
#RUN chmod +x /tmp/run.sh
#CMD ["/tmp/run.sh"]